### ISSUE TITLE
Buddy can't be used under non-root and non-manticore

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#166]
Buddy can be run only under root and `manticore`, e.g.:

root:
```
root@78c483766894:~# /usr/share/manticore/modules/manticore-buddy/bin/manticore-buddy
Buddy v1.1.1 started 127.0.0.1:44159
Loaded plugins:
  core: empty-string, backup, emulate-elastic, insert, select, show, cli-table, plugin, test, insert-mva
  local:
  extra:
^C
```

manticore:
```
root@78c483766894:~# sudo -u manticore /usr/share/manticore/modules/manticore-buddy/bin/manticore-buddy
Buddy v1.1.1 started 127.0.0.1:45099
Loaded plugins:
  core: empty-string, backup, emulate-elastic, insert, select, show, cli-table, plugin, test, insert-mva
  local:
  extra:
^C
```

It fails when run under any other user:
```
root@78c483766894:~# useradd random
root@78c483766894:~# sudo -u random /usr/share/manticore/modules/manticore-buddy/bin/manticore-buddy

Fatal error: Uncaught Exception: Unable to read composer file in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php:105
Stack trace:
#0 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(365): Manticoresearch\Buddy\Core\Plugin\Pluggable->getList()
#1 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(345): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchPlugins()
#2 /usr/share/manticore/modules/manticore-buddy/src/Lib/QueryProcessor.php(103): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchExtraPlugins()
#3 /usr/share/manticore/modules/manticore-buddy/src/main.php(31): Manticoresearch\Buddy\Base\Lib\QueryProcessor::init()
#4 {main}
  thrown in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php on line 105
```

It also fails when run via searchd:
```
root@78c483766894:/tmp# cat manti.conf
searchd {
   listen = 9315:mysql
   listen = 9316
   data_dir = .
   pid_file = 9315.pid
   log = searchd.log
   binlog_path =
}

root@78c483766894:/tmp# sudo -u random searchd -c manti.conf
Manticore 6.2.13 85ffbbbb8@230929 dev (columnar 2.2.5 b8be4eb@230928) (secondary 2.2.5 b8be4eb@230928)

root@78c483766894:/tmp# tail searchd.log
[Thu Oct  5 10:53:09.785 2023] [1905] WARNING: [BUDDY] invalid output, should be 'Buddy ver, started address:port', got '
Fatal error: Uncaught Exception: Unable to read composer file in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php:105
Stack trace:
#0 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(365): Manticoresearch\Buddy\Core\Plugin\Pluggable->getList()
#1 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(345): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchPlugins()
#2 /usr/share/manticore/modules/manticore-buddy/src/Lib/QueryProcessor.php(103): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchExtraPlugins()
#3 /usr/share/manticore/modules/manticore-buddy/src/main.php(31): Manticoresearch\Buddy\Base\Lib\QueryProcessor::init()
#4 {main}
  thrown in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-
[Thu Oct  5 10:53:09.785 2023] [1905] [BUDDY] restart amount of attempts (3) has been exceeded
```

The task is to fix it. It's important for users to be able to run buddy if they can run searchd.

**Comment by sanikolaev** [comment]
As discussed, the root cause of this is that Buddy has to write to plugin_dir which requires the user use a custom plugin_dir in case they want to run Manticore under non-root/manticore.

So the task is to show a better error instead of:
```
[Thu Oct 12 06:29:24.196 2023] [804] WARNING: [BUDDY] invalid output, should be 'Buddy ver, started address:port', got '
Fatal error: Uncaught Exception: Unable to read composer file in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php:105
Stack trace:
#0 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(365): Manticoresearch\Buddy\Core\Plugin\Pluggable->getList()
#1 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(345): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchPlugins()
#2 /usr/share/manticore/modules/manticore-buddy/src/Lib/QueryProcessor.php(103): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchExtraPlugins()
#3 /usr/share/manticore/modules/manticore-buddy/src/main.php(30): Manticoresearch\Buddy\Base\Lib\QueryProcessor::init()
#4 {main}
  thrown in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-c
```

**Comment by donhardman** [comment]
Improve the error message in the main branch and enhance the logic to handle exceptions during initialization and server start. Display the stack trace only when in debug mode, while showing only the error message without the stack trace in other cases.

**Comment by sanikolaev** [comment]
Here's what I get in Ubuntu Jammy:
```
root@e80d4c7d3785:~# sudo -u random /usr/share/manticore/modules/manticore-buddy/bin/manticore-buddy
Error while initialization: Unable to read composer file
```

with the following packages installed:

```
manticore-backup/jammy,now 1.1.9-23110305-f221bfe all [installed]
manticore-buddy/jammy,now 2.0.3-23110304-379f65d all [installed]
manticore-columnar-lib-dbgsym/jammy,now 2.2.5-230928-b8be4eb amd64 [installed]
manticore-columnar-lib/jammy,now 2.2.5-230928-b8be4eb amd64 [installed]
manticore-common/jammy,now 6.2.13-231102-bd6b489b3 all [installed]
manticore-dev/jammy,now 6.2.13-231102-bd6b489b3 all [installed,automatic]
manticore-executor/jammy,now 1.0.7-23110304-176eef7 amd64 [installed]
manticore-extra/jammy,now 1.0.7-23110304-176eef7 all [installed]
manticore-icudata-65l/jammy,now 5.0.3-221123-d2d9e5e56 all [installed]
manticore-repo/now 0.0.4 all [installed,local]
manticore-server-core-dbgsym/jammy,now 6.2.13-231102-bd6b489b3 amd64 [installed]
manticore-server-core/jammy,now 6.2.13-231102-bd6b489b3 amd64 [installed]
manticore-server/jammy,now 6.2.13-231102-bd6b489b3 amd64 [installed]
manticore-tools-dbgsym/jammy,now 6.2.13-231102-bd6b489b3 amd64 [installed]
manticore-tools/jammy,now 6.2.13-231102-bd6b489b3 amd64 [installed]
manticore/jammy,now 6.2.13-231102-bd6b489b3 amd64 [installed]
```

**Comment by donhardman** [comment]
Due to this modification in the plugin, the proper version did not get updated. I have now updated the dependencies.

Error should be: `Unable to read composer file from plugin dir: $composerFile, make sure that you have correct permissions on plugin dir`
