### ISSUE TITLE
Failed to open stream: No such file or directory manticore.json

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#305]
### Bug Description:

There is an issue when we collect metrics with the daemon that has no tables and just invited while in this case `manticore.json` is missing:

```
[BUDDY] Fatal error: Uncaught ErrorException: file_get_contents(/var/lib/manticore/manticore.json): Failed to open stream: No such file or directory in /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php:394
[BUDDY] Stack trace:
[BUDDY] #0 [internal function]: buddy_error_handler(2, 'file_get_conten...', '/usr/share/mant...', 394)
[BUDDY] #1 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(394): file_get_contents('/var/lib/mantic...')
[BUDDY] #2 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(257): Manticoresearch\Buddy\Base\Lib\Metric->getVolumeMetrics()
[BUDDY] #3 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(208): Manticoresearch\Buddy\Base\Lib\Metric->snapshot()
[BUDDY] #4 /usr/share/manticore/modules/manticore-buddy/src/Lib/MetricThread.php(102): Manticoresearch\Buddy\Base\Lib\Metric->checkAndSnapshot(300)
[BUDDY] #5 [internal function]: Manticoresearch\Buddy\Base\Lib\MetricThread::Manticoresearch\Buddy\Base\Lib\{closure}(Object(Swoole\Process))
[BUDDY] #6 {main}
```

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by donhardman** [comment]
Implemented: https://github.com/manticoresoftware/manticoresearch-buddy/pull/306

**Comment by donhardman** [comment]
Merged, closing.
